Added debug to YAML

diff --git a/.github/workflows/monthly_pipeline.yml b/.github/workflows/monthly_pipeline.yml
--- a/.github/workflows/monthly_pipeline.yml
+++ b/.github/workflows/monthly_pipeline.yml
@@ -32,7 +32,13 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r NYC_Taxi_Analytics_Pipeline/requirements.txt
-
+      - name: Debug secrets presence
+        run: |
+          if [ -z "${{ secrets.YELLOW_TAXI_AWS_ACCESS_KEY_ID }}" ]; then
+            echo "AWS KEY MISSING"
+            exit 1
+          fi
+          echo "AWS KEY EXISTS"
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
